apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: elasticsearch
spec:
  cloudInstances:
    classReference:
      kind: AWSInstanceClass
      name: elasticsearch
    maxPerZone: 1
    minPerZone: 1
    zones:
    - eu-west-1a
    - eu-west-1b
    - eu-west-1c
  disruptions:
    approvalMode: Automatic
  nodeTemplate:
    labels:
      node-role/elasticsearch: ""
    taints:
    - effect: NoSchedule
      key: dedicated
      value: elasticsearch
  nodeType: CloudEphemeral