apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: frontend
spec:
  chaos:
    mode: Disabled
  cloudInstances:
    classReference:
      kind: AWSInstanceClass
      name: frontend
    maxPerZone: 1
    minPerZone: 1
    zones:
    - eu-west-1a
    - eu-west-1b
  disruptions:
    approvalMode: Automatic
  nodeTemplate:
    labels:
      node-role.deckhouse.io/frontend: ""
    taints:
    - effect: NoExecute
      key: dedicated.deckhouse.io
      value: frontend
  nodeType: CloudEphemeral
